export const siteConfig = {
  name: "Fardin Ahsan",
  title: "Full Stack Developer",
  url: "https://fardinahsan.dev",
  email: "fardin.ahsan75@gmail.com",
  phone: "+880 1759552872",
  location: "Dhaka, Bangladesh",
  calendarUrl: "https://calendar.app.google/muUJCTnbtDe1fF5E7",
  social: {
    linkedin: "https://www.linkedin.com/in/ahsan-fardin/",
    github: "https://github.com/jsxFardin",
    facebook: "https://www.facebook.com/jsxfardin/",
    twitter: "https://x.com/FardinAhsan13",
  },
};

export const projects = [
  {
    name: "Agilibo – Agile SaaS Platform",
    description:
      "Comprehensive Agile platform supporting backlog, sprint, planning, retrospectives, and more, with AI-powered insights. Supports two-way integration with Jira & Azure DevOps, designed for multi-team and multi-company environments.",
    problem: "Teams struggle with fragmented agile tools and lack of unified insights.",
    solution: "Unified platform with AI-powered analytics and Jira/Azure DevOps integration.",
    features: [
      "AI-powered insights and automated reporting",
      "Two-way integration with Jira & Azure DevOps",
      "Gamified features and collaborative tools",
      "Real-time notifications and dashboards",
      "Role-based access control for secure multi-level team management",
      "Optimized system performance for large-scale enterprise data",
    ],
    technologies: [
      "Vue.js",
      "Laravel",
      "Node.js",
      "Redis",
      "Elasticsearch",
      "AI Integration",
      "Real-time Systems",
      "Jira Integration",
      "Azure",
      "Docker",
      "Microservice",
      "Payment Gateway",
      "Analytics",
      "Multi-language",
    ],
    link: "https://www.agilibo.info",
    company: "Kaz Software LTD",
    image: "/images/projects/agilibo.png",
  },
  {
    name: "Alternative Learning Programme (ALP)",
    description:
      "Non-formal education initiative in Bangladesh for out-of-school and marginalized youth, focusing on skills development and empowerment.",
    problem: "Out-of-school youth lack access to structured learning and skills development.",
    solution: "Digital platform for course management, progress tracking, and impact analytics across districts.",
    features: [
      "Student registration and course management",
      "Progress tracking and analytics",
      "Monitoring learning outcomes across multiple districts",
      "Responsive web interface for low-end devices",
      "Program impact analytics and reporting",
    ],
    technologies: [
      "Vue.js",
      "Laravel",
      "Analytics",
      "Responsive Design",
      "Multi-district Management",
      "Google Maps API",
      "Multi-language",
    ],
    link: "https://alprtm.com/",
    company: "UNICEF Bangladesh",
    image: "/images/projects/alp.png",
  },
  {
    name: "Prospeneo – Real Estate Software",
    description:
      "Developed features for AI-powered lead generation, sales funnel management, websites, email marketing, and analytics.",
    problem: "Real estate agents need efficient lead management and sales tracking.",
    solution: "AI-powered CRM with lead generation, funnel management, and analytics.",
    features: [
      "AI-powered lead generation and sales funnel management",
      "CRM solutions for agents and agencies",
      "Custom dashboards for tracking leads and deals",
      "Payment gateway integration",
      "Cross-platform consistency for web and mobile",
      "Email marketing and analytics integration",
    ],
    technologies: [
      "Vue.js",
      "Laravel",
      "AI Integration",
      "CRM",
      "Payment Gateway",
      "Analytics",
      "Google Maps API",
      "Email Marketing",
      "Website Builder",
      "Real-time Tracking",
      "Multi-currency",
      "Multi-language",
    ],
    link: "https://www.prospeneo.com/",
    company: "Prospeneo",
    image: "/images/projects/prospeneo.jpg",
  },
  {
    name: "Robishop – E-commerce Platform",
    description:
      "Built product catalog, payment integration, order processing, and delivery tracking for Robi Axiata Ltd.",
    problem: "Telecom operator needed a scalable e-commerce platform for their customers.",
    solution: "Full-featured PWA with product catalog, payments, order tracking, and loyalty programs.",
    features: [
      "Product catalog and payment integration",
      "Order processing and delivery tracking",
      "Returns management and customer support",
      "Promotional campaigns and coupon management",
      "Loyalty programs to boost sales",
      "Analytics dashboards for sales and user behavior",
    ],
    technologies: [
      "Vue Storefront",
      "Express.js",
      "Magento 2",
      "PWA",
      "Redis",
      "Elasticsearch",
      "Payment Gateway",
      "Analytics",
      "Multi-language",
      "Real-time Tracking",
      "Docker",
      "AWS",
    ],
    link: "https://robishop.com.bd",
    company: "Robi Axiata Limited",
    image: "/images/projects/robishop.webp",
  },
  {
    name: "Sendparcel – International Parcel Delivery",
    description:
      "Simplified global shipping with integrations for DHL, FedEx, TNT, and GLS across 220+ countries.",
    problem: "Businesses need simplified multi-carrier international shipping.",
    solution: "Unified platform for booking, tracking, and price comparison across 220+ countries.",
    features: [
      "Global shipping with multiple courier integrations",
      "Booking, tracking, and price comparison",
      "Automated shipping rate calculation",
      "Multi-currency payment gateways",
      "Real-time shipment updates and notifications",
      "Admin dashboards for operational efficiency",
    ],
    technologies: [
      "Symfony",
      "PHP",
      "Payment Gateway",
      "Shipping API",
      "Multi-currency",
      "Real-time Tracking",
      "AI Integration",
    ],
    link: "https://www.sendparcel.com/",
    company: "Sendparcel",
    image: "/images/projects/sendparcel.jpg",
  },
];

export const services = [
  {
    title: "Custom Software Development",
    description: "Enterprise platforms, ERP, dashboards, booking systems — fully modular and scalable.",
    accentColor: "blue",
  },
  {
    title: "AI & ML Integration",
    description: "From predictive analytics to medical insights using RAG, embedding, and OpenAI models.",
    accentColor: "purple",
  },
  {
    title: "DevOps & Cloud",
    description: "Docker, AWS, Azure, CI/CD pipelines, and infrastructure as code for scalable deployments.",
    accentColor: "cyan",
  },
  {
    title: "Mobile App Development",
    description: "High-performance iOS and Android apps that enhance customer experience with seamless user interfaces.",
    accentColor: "emerald",
  },
 
];

export const technologies = [
  "Laravel",
  "Vue.js",
  "React",
  "Node.js",
  "AI Integration",
  "Next.js",
  "Nuxt.js",
  "React Native",
  "TypeScript",
  "PHP",
  "Tailwind CSS",
  "Docker",
  "AWS",
  "Azure",
  "MySQL",
  "PostgreSQL",
  "Redis",
  "MongoDB",
  "GraphQL",
  "REST API",
];

export const techCategories = [
  {
    title: "Frontend",
    techs: ["React", "Vue.js", "Next.js", "Nuxt.js", "React Native", "Tailwind CSS", "TypeScript"],
    accent: "pink",
  },
  {
    title: "Backend",
    techs: ["Laravel", "Node.js", "PHP", "GraphQL", "REST API", "AI Integration"],
    accent: "purple",
  },
  {
    title: "Database",
    techs: ["MySQL", "PostgreSQL", "Redis", "MongoDB"],
    accent: "cyan",
  },
  {
    title: "DevOps & Cloud",
    techs: ["Docker", "AWS", "Azure"],
    accent: "emerald",
  },
];

export const testimonials = [
  {
    quote: "Fardin did an excellent job on our Laravel SaaS project. His deep knowledge of Laravel and attention to detail resulted in high-quality deliverables that met our requirements perfectly. He was communicative, reliable, and proactive in addressing challenges. His contributions significantly improved our project. Highly recommended for anyone seeking a skilled Laravel developer!",
    author: "Ziad Iqbal",
    role: "CEO",
    company: "Agilibo",
    projectTag: "SaaS",
    rating: 5,
  },
  {
    quote: "Good work. Fardin is experienced in Vue.js and a pleasure to work with.",
    author: "Tony Duong",
    role: "Project Manager",
    company: "Econumerica Software",
    projectTag: "CRM",
    rating: 5,
  },
  {
    quote: "Thanks for your fast delivery of high quality work.",
    author: "Christof Moser",
    role: "CEO",
    company: "Actra AG",
    projectTag: "E-commerce",
    rating: 5,
  },
  {
    quote: "Fardin is a great guy to work with. An expert in web development and he completed the job with 100% success. I would recommend Fardin to anyone.",
    author: "Calum Stewart",
    role: "Project Delivery Lead",
    company: "Investoo Group",
    projectTag: "ERP",
    rating: 5,
  },
];
